import type { Metadata } from "next";

import "../../styles/index.scss";
import { Header } from "@/widgets/mainblocks/header";
import Footer from "@/widgets/mainblocks/footer";
import { ModalAuth } from "@/widgets/auth/modal-auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
        <ModalAuth />
      </body>
    </html>
  );
}
