import { ICardVacancy } from "@/entity/vacancy/ui/card-vacancy";

export const mockVacancies: Omit<ICardVacancy, "children">[] = [
  {
    id: 1,
    title: "Frontend разработчик",
    resumeParams: ["React", "TypeScript", "Redux", "3+ года"],
    location: "Москва",
    startPrice: "150 000",
    endPrice: "250 000",
  },
  {
    id: 2,
    title: "Backend разработчик",
    resumeParams: ["Node.js", "PostgreSQL", "Docker", "5+ лет"],
    location: "Санкт-Петербург",
    startPrice: "180 000",
    endPrice: "300 000",
  },
  {
    id: 3,
    title: "UI/UX дизайнер",
    resumeParams: ["Figma", "Sketch", "Adobe XD", "2+ года"],
    location: "Удаленно",
    startPrice: "80 000",
    endPrice: "150 000",
  },
  {
    id: 4,
    title: "DevOps инженер",
    resumeParams: ["AWS", "Kubernetes", "CI/CD", "4+ года"],
    location: "Новосибирск",
    startPrice: "200 000",
    endPrice: "350 000",
  },
  {
    id: 5,
    title: "QA Engineer",
    resumeParams: ["Автотесты", "Selenium", "Python", "3+ года"],
    location: "Казань",
    startPrice: "120 000",
    endPrice: "180 000",
  },
  {
    id: 6,
    title: "Mobile разработчик",
    resumeParams: ["React Native", "iOS", "Android", "4+ года"],
    location: "Москва",
    startPrice: "170 000",
    endPrice: "280 000",
  },
  {
    id: 7,
    title: "Data Scientist",
    resumeParams: ["Python", "Machine Learning", "TensorFlow", "3+ года"],
    location: "Удаленно",
    startPrice: "160 000",
    endPrice: "250 000",
  },
  {
    id: 8,
    title: "Product Manager",
    resumeParams: ["Agile", "Scrum", "Аналитика", "5+ лет"],
    location: "Санкт-Петербург",
    startPrice: "200 000",
    endPrice: "400 000",
  },
  {
    id: 9,
    title: "Системный аналитик",
    resumeParams: ["UML", "BPMN", "SQL", "4+ года"],
    location: "Екатеринбург",
    startPrice: "140 000",
    endPrice: "220 000",
  },
  {
    id: 10,
    title: "Fullstack разработчик",
    resumeParams: ["React", "Node.js", "MongoDB", "3+ года"],
    location: "Нижний Новгород",
    startPrice: "130 000",
    endPrice: "200 000",
  },
  {
    id: 11,
    title: "Архитектор ПО",
    resumeParams: ["Microservices", "System Design", "Java", "7+ лет"],
    location: "Москва",
    startPrice: "300 000",
    endPrice: "500 000",
  },
  {
    id: 12,
    title: "Безопасность ИТ",
    resumeParams: ["Pentesting", "SIEM", "Incident Response", "4+ года"],
    location: "Удаленно",
    startPrice: "180 000",
    endPrice: "280 000",
  },
  {
    id: 13,
    title: "Technical Writer",
    resumeParams: ["Документация", "API", "Английский", "2+ года"],
    location: "Ростов-на-Дону",
    startPrice: "90 000",
    endPrice: "140 000",
  },
  {
    id: 14,
    title: "Game Developer",
    resumeParams: ["Unity", "C#", "3D графика", "3+ года"],
    location: "Краснодар",
    startPrice: "100 000",
    endPrice: "180 000",
  },
  {
    id: 15,
    title: "Blockchain разработчик",
    resumeParams: ["Solidity", "Web3", "Smart Contracts", "2+ года"],
    location: "Удаленно",
    startPrice: "200 000",
    endPrice: "350 000",
  },
];
